// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('index', function() {
  this.timeout(30000);
  
  let driver
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
  });

  async function login(){
    await driver.get("http://localhost/SaldoPositivo/");
    await driver.findElement(By.id("email_logar")).click();
    await driver.findElement(By.id("email_logar")).sendKeys("jheymisonbao@live.com");
    await driver.findElement(By.id("senha_logar")).click();
    await driver.findElement(By.id("senha_logar")).sendKeys("Misson201369");
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
  }

  it('index', async function() {
    login();
  });
 
});