// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver'); // Importando dependencias do Selenium

describe('index', function() {
  this.timeout(30000)
  
  let driver
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
  });

  // Função que realiza o cadastro 
  async function cadastrar_usuario(){
    await driver.get("http://localhost/SaldoPositivo/index.php?page=usuarios&sec=cadastrar_usuario");
    await driver.findElement(By.id("nome_cadastrar")).click();
    await driver.findElement(By.id("nome_cadastrar")).sendKeys("Luana Aquino");
    await driver.findElement(By.id("email_cadastrar")).click();
    await driver.findElement(By.id("email_cadastrar")).sendKeys("Luana@gmail.com");
    await driver.findElement(By.id("senha_cadastrar")).click();
    await driver.findElement(By.id("senha_cadastrar")).sendKeys("Luhh1955");
    await driver.findElement(By.id("conf_senha")).click();
    await driver.findElement(By.id("conf_senha")).sendKeys("Luhh1955");
    await driver.findElement(By.css(".btn-success")).click();
  };

  it('index', async function() {
    cadastrar_usuario(); //Aplicando a função
  });
 
})
