// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver'); // Importando dependencias do Selenium

describe('index', function() {
  this.timeout(30000)
  
  let driver
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
  });

  async function cadastrar_nova_meta(){
    await driver.get("http://localhost/SaldoPositivo");
    await driver.findElement(By.id("email_logar")).click();
    await driver.findElement(By.id("email_logar")).sendKeys("jheymisonbao@live.com");
    await driver.findElement(By.id("senha_logar")).click();
    await driver.findElement(By.id("senha_logar")).sendKeys("Misson201369");
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
    await driver.get("http://localhost/SaldoPositivo/main.php?page=metas&sec=cadastrar_metas");
    await driver.findElement(By.css(".filter-option-inner-inner")).click();
    await driver.findElement(By.linkText("Video-Game")).click();
    await driver.findElement(By.id("descricao")).sendKeys("Quero comprar um PS5 Novo");
    await driver.findElement(By.id("valor_meta")).sendKeys("7000");
    await driver.findElement(By.css(".btn-primary")).click();
  }

  it('index', async function() {
    cadastrar_nova_meta(); //Aplicando a função
  });
 
})
